


import React from 'react';
import {Icon, Flex} from 'antd-mobile'

import {nativeClick} from '../../utils/native-sdk'
import './style/style.less';

export default class VipActive extends React.Component{
    constructor(props) {
        super(props)
        this.state = {
            id: '',

        }
        this.titleList = ['美妆个护','保健养生','食品酒水','母婴用品','家居家纺'];
        this.goods = [
            [
                {
                    bigpic:
                        "http://mlgwxyt-1254277558.picsh.myqcloud.com/upload/img/171012163610.jpg",
                    category:
                        "56",
                    gdesc:
                        null,
                    good_id:
                        1542,
                    gorder:
                        0,
                    gtitle:
                        "巴卡尔兰混合水果干谷物棒240g",
                    id:
                        1542,
                    price:
                        37.8,
                    standard:
                        "/盒",
                    stitle:
                        "巴卡尔兰混合水果干谷物棒240g",
                    tags:
                        null,
                    type:
                        "0",
                    vipprice:
                        31.5,
                    zkprice:
                        31.5
                },
                {
                    bigpic:
                        "http://mlgwxyt-1254277558.picsh.myqcloud.com/upload/img/171012164027.jpg",
                    category:
                        "56",
                    gdesc:
                        null,
                    good_id:
                        1544,
                    gorder:
                        0,
                    gtitle:
                        "巴卡尔兰杏干可可牛奶味谷物棒240g ",
                    id:
                        1544,
                    price:
                        37.8,
                    standard:
                        "/盒",
                    stitle:
                        "巴卡尔兰杏干可可牛奶味谷物棒240g ",
                    tags:
                        null,
                    type:
                        "0",
                    vipprice:
                        31.5,
                    zkprice:
                        31.5
                },
                {
                    bigpic:
                        "http://mlgwxyt-1254277558.picsh.myqcloud.com/upload/img/171017161054.jpg",
                    category:
                        "56",
                    gdesc:
                        null,
                    good_id:
                        533,
                    gorder:
                        0,
                    gtitle:
                        "乐事多蓝莓干100g",
                    id:
                        533,
                    price:
                        40,
                    standard:
                        "/袋",
                    stitle:
                        "乐事多蓝莓干100g",
                    tags:
                        null,
                    type:
                        "0",
                    vipprice:
                        33.4,
                    zkprice:
                        33.4
                },
                {
                    bigpic:
                        "http://mlgwxyt-1254277558.picsh.myqcloud.com/upload/img/171024151155.jpg",
                    category:
                        "66",
                    gdesc:
                        null,
                    good_id:
                        799,
                    gorder:
                        1,
                    gtitle:
                        "卡萨布兰卡酒庄天逸珍藏系列赤霞珠750ml",
                    id:
                        799,
                    price:
                        258,
                    standard:
                        "/瓶",
                    stitle:
                        "卡萨布兰卡酒庄天逸珍藏系列赤霞珠750ml",
                    tags:
                        "",
                    type:
                        "0",
                    vipprice:
                        209.4,
                    zkprice:
                        209.4
                },
                {
                    bigpic:
                        "http://mlgwxyt-1254277558.picsh.myqcloud.com/upload/img/1510044879827.jpg",
                    category:
                        "66",
                    gdesc:
                        null,
                    good_id:
                        1634,
                    gorder:
                        50,
                    gtitle:
                        "西班牙 霓梦の幻灭重生 起泡酒（柠檬味）750ML-预售",
                    id:
                        1634,
                    price:
                        132,
                    standard:
                        "/瓶",
                    stitle:
                        "西班牙 霓梦の幻灭重生 起泡酒（柠檬味）750ML-预售",
                    tags:
                        "",
                    type:
                        "0",
                    vipprice:
                        68,
                    zkprice:
                        68
                },
                {
                    bigpic:
                        "http://mlgwxyt-1254277558.picsh.myqcloud.com/upload/img/1510136032831.jpg",
                    category:
                        "66",
                    gdesc:
                        null,
                    good_id:
                        1656,
                    gorder:
                        50,
                    gtitle:
                        "瓦伦丁小麦啤酒（500ml听装）",
                    id:
                        1656,
                    price:
                        19,
                    standard:
                        "/厅",
                    stitle:
                        "瓦伦丁小麦啤酒（500ml听装）",
                    tags:
                        "",
                    type:
                        "0",
                    vipprice:
                        19,
                    zkprice:
                        19
                }
            ],
            [
                {
                    bigpic:
                        "http://mlgwxyt-1254277558.picsh.myqcloud.com/upload/img/171011151426.png",
                    category:
                        "26",
                    gdesc:
                        null,
                    good_id:
                        1430,
                    gorder:
                        0,
                    gtitle:
                        "谜尚魅力 润颜嫩白柔护霜 SPF30+ PA+++ 21#  50ml",
                    id:
                        1430,
                    price:
                        134,
                    standard:
                        "/支",
                    stitle:
                        "谜尚魅力 润颜嫩白柔护霜 SPF30+ PA+++ 21#  50ml",
                    tags:
                        null,
                    type:
                        "0",
                    vipprice:
                        113.5,
                    zkprice:
                        113.5
                },
                {
                    bigpic:
                        "http://mlgwxyt-1254277558.picsh.myqcloud.com/upload/img/171011184755.jpg",
                    category:
                        "26",
                    gdesc:
                        "面膜",
                    good_id:
                        1526,
                    gorder:
                        0,
                    gtitle:
                        "丽得姿美蒂优氨基酸收缩毛孔面膜",
                    id:
                        1526,
                    price:
                        90,
                    standard:
                        "/盒",
                    stitle:
                        "丽得姿美蒂优氨基酸收缩毛孔面膜",
                    tags:
                        "",
                    type:
                        "0",
                    vipprice:
                        74.8,
                    zkprice:
                        74.8
                },
                {
                    bigpic:
                        "http://mlgwxyt-1254277558.picsh.myqcloud.com/upload/img/171011184519.jpg",
                    category:
                        "26",
                    gdesc:
                        "面膜",
                    good_id:
                        1523,
                    gorder:
                        0,
                    gtitle:
                        "丽得姿美蒂优氨基酸净肤面膜",
                    id:
                        1523,
                    price:
                        90,
                    standard:
                        "/盒",
                    stitle:
                        "丽得姿美蒂优氨基酸净肤面膜",
                    tags:
                        "",
                    type:
                        "0",
                    vipprice:
                        74.8,
                    zkprice:
                        74.8
                },
                {
                    bigpic:
                        "http://mlgwxyt-1254277558.picsh.myqcloud.com/upload/img/171011184644.jpg",
                    category:
                        "26",
                    gdesc:
                        "面膜",
                    good_id:
                        1524,
                    gorder:
                        0,
                    gtitle:
                        "丽得姿美蒂优氨基酸深层补水面膜10片装",
                    id:
                        1524,
                    price:
                        90,
                    standard:
                        "/盒",
                    stitle:
                        "丽得姿美蒂优氨基酸深层补水面膜10片装",
                    tags:
                        "",
                    type:
                        "0",
                    vipprice:
                        74.8,
                    zkprice:
                        74.8
                },
                {
                    bigpic:
                        "http://mlgwxyt-1254277558.picsh.myqcloud.com/upload/img/171011185245.jpg",
                    category:
                        "26",
                    gdesc:
                        null,
                    good_id:
                        1429,
                    gorder:
                        0,
                    gtitle:
                        "谜尚魅力 润颜靓白柔护霜 SPF30+ PA+++ 23# 50ml",
                    id:
                        1429,
                    price:
                        134,
                    standard:
                        "/支",
                    stitle:
                        "谜尚魅力 润颜靓白柔护霜 SPF30+ PA+++ 23# 50ml",
                    tags:
                        null,
                    type:
                        "0",
                    vipprice:
                        113.5,
                    zkprice:
                        113.5
                },
                {
                    bigpic:
                        "http://mlgwxyt-1254277558.picsh.myqcloud.com/upload/img/171019153431.jpg",
                    category:
                        "26",
                    gdesc:
                        null,
                    good_id:
                        1460,
                    gorder:
                        0,
                    gtitle:
                        "日本莎娜豆乳美肤浓润化妆水200ml",
                    id:
                        1460,
                    price:
                        100,
                    standard:
                        "/瓶",
                    stitle:
                        "日本莎娜豆乳美肤浓润化妆水200ml",
                    tags:
                        "",
                    type:
                        "0",
                    vipprice:
                        69,
                    zkprice:
                        69
                }
            ],
            [
                {
                    bigpic:
                        "http://mlgwxyt-1254277558.picsh.myqcloud.com/upload/img/171010144616.jpg",
                    category:
                        "33",
                    gdesc:
                        null,
                    good_id:
                        1415,
                    gorder:
                        0,
                    gtitle:
                        "康力士牌三文鱼油维生素E软胶囊300粒",
                    id:
                        1415,
                    price:
                        393,
                    standard:
                        "/瓶",
                    stitle:
                        "康力士牌三文鱼油维生素E软胶囊300粒",
                    tags:
                        "",
                    type:
                        "0",
                    vipprice:
                        194,
                    zkprice:
                        194
                },
                {
                    bigpic:
                        "http://mlgwxyt-1254277558.picsh.myqcloud.com/upload/img/171025142138.jpg",
                    category:
                        "33",
                    gdesc:
                        null,
                    good_id:
                        1425,
                    gorder:
                        0,
                    gtitle:
                        "天美健牌维生素Ｅ软胶囊500mg",
                    id:
                        1425,
                    price:
                        193,
                    standard:
                        "/瓶",
                    stitle:
                        "天美健牌维生素Ｅ软胶囊500mg",
                    tags:
                        null,
                    type:
                        "0",
                    vipprice:
                        165.4,
                    zkprice:
                        165.4
                },
                {
                    bigpic:
                        "http://mlgwxyt-1254277558.picsh.myqcloud.com/upload/img/171011174841.jpg",
                    category:
                        "33",
                    gdesc:
                        null,
                    good_id:
                        708,
                    gorder:
                        1,
                    gtitle:
                        "康力士儿童水果口味糖果60粒",
                    id:
                        708,
                    price:
                        132,
                    standard:
                        "/瓶",
                    stitle:
                        "康力士儿童水果口味糖果60粒",
                    tags:
                        null,
                    type:
                        "0",
                    vipprice:
                        112.6,
                    zkprice:
                        112.6
                },
                {
                    bigpic:
                        "http://mlgwxyt-1254277558.picsh.myqcloud.com/upload/img/171011160143.jpg",
                    category:
                        "33",
                    gdesc:
                        null,
                    good_id:
                        930,
                    gorder:
                        1,
                    gtitle:
                        "康力士®红太胶囊60粒",
                    id:
                        930,
                    price:
                        303,
                    standard:
                        "/瓶",
                    stitle:
                        "康力士®红太胶囊60粒",
                    tags:
                        "",
                    type:
                        "0",
                    vipprice:
                        149,
                    zkprice:
                        149
                },
                {
                    bigpic:
                        "http://mlgwxyt-1254277558.picsh.myqcloud.com/upload/img/171011163426.jpg",
                    category:
                        "33",
                    gdesc:
                        null,
                    good_id:
                        944,
                    gorder:
                        1,
                    gtitle:
                        "康力士®鲨鱼软骨粉胶囊100粒",
                    id:
                        944,
                    price:
                        303,
                    standard:
                        "/瓶",
                    stitle:
                        "康力士®鲨鱼软骨粉胶囊100粒",
                    tags:
                        "",
                    type:
                        "0",
                    vipprice:
                        149,
                    zkprice:
                        149
                },
                {
                    bigpic:
                        "http://mlgwxyt-1254277558.picsh.myqcloud.com/upload/img/171011162758.jpg",
                    category:
                        "33",
                    gdesc:
                        null,
                    good_id:
                        953,
                    gorder:
                        1,
                    gtitle:
                        "康力士牌牛初乳片60片",
                    id:
                        953,
                    price:
                        203,
                    standard:
                        "/瓶",
                    stitle:
                        "康力士牌牛初乳片60片",
                    tags:
                        "",
                    type:
                        "0",
                    vipprice:
                        99,
                    zkprice:
                        99
                },
            ],
            [
                {
                    bigpic:
                        "http://mlgwxyt-1254277558.picsh.myqcloud.com/upload/img/171019165236.jpg",
                    category:
                        "27",
                    gdesc:
                        null,
                    good_id:
                        1371,
                    gorder:
                        1,
                    gtitle:
                        "韩国菡琉儿童草莓味牙膏  60g",
                    id:
                        1371,
                    price:
                        28,
                    standard:
                        "/盒",
                    stitle:
                        "韩国菡琉儿童草莓味牙膏  60g",
                    tags:
                        null,
                    type:
                        "0",
                    vipprice:
                        20.2,
                    zkprice:
                        20.2
                },
                {
                    bigpic:
                        "http://mlgwxyt-1254277558.picsh.myqcloud.com/upload/img/171027164827.jpg",
                    category:
                        "27",
                    gdesc:
                        null,
                    good_id:
                        1627,
                    gorder:
                        50,
                    gtitle:
                        "土耳其原装进口正品ViKing  蔚净儿童固齿牙膏75ml【预售】",
                    id:
                        1627,
                    price:
                        15.9,
                    standard:
                        "/支",
                    stitle:
                        "土耳其原装进口正品ViKing 蔚净儿童固齿牙膏75ml【预售】",
                    tags:
                        "",
                    type:
                        "0",
                    vipprice:
                        10.9,
                    zkprice:
                        10.9
                },
                {
                    bigpic:
                        "http://mlgwxyt-1254277558.picsh.myqcloud.com/upload/img/171019171124.jpg",
                    category:
                        "27",
                    gdesc:
                        null,
                    good_id:
                        1370,
                    gorder:
                        1,
                    gtitle:
                        "韩国菡琉儿童苹果味牙膏  60g",
                    id:
                        1370,
                    price:
                        28,
                    standard:
                        "/盒",
                    stitle:
                        "韩国菡琉儿童苹果味牙膏  60g",
                    tags:
                        null,
                    type:
                        "0",
                    vipprice:
                        20.2,
                    zkprice:
                        20.2
                },
                {
                    bigpic:
                        "http://mlgwxyt-1254277558.picsh.myqcloud.com/upload/img/171101112207.jpg",
                    category:
                        "22",
                    gdesc:
                        null,
                    good_id:
                        739,
                    gorder:
                        50,
                    gtitle:
                        "安诺尼摩德纳黑醋250ml",
                    id:
                        739,
                    price:
                        40,
                    standard:
                        "/瓶",
                    stitle:
                        "安诺尼摩德纳黑醋250ml",
                    tags:
                        null,
                    type:
                        "0",
                    vipprice:
                        30.8,
                    zkprice:
                        30.8
                },
                {
                    bigpic:
                        "http://mlgwxyt-1254277558.picsh.myqcloud.com/upload/img/171102103123.jpg",
                    category:
                        "22",
                    gdesc:
                        null,
                    good_id:
                        740,
                    gorder:
                        50,
                    gtitle:
                        "安诺尼葡萄酒醋调味酱250ml",
                    id:
                        740,
                    price:
                        40,
                    standard:
                        "/瓶",
                    stitle:
                        "安诺尼葡萄酒醋调味酱250ml",
                    tags:
                        null,
                    type:
                        "0",
                    vipprice:
                        30.8,
                    zkprice:
                        30.8
                },
                {
                    bigpic:
                        "http://mlgwxyt-1254277558.picsh.myqcloud.com/upload/img/171104103919.jpg",
                    category:
                        "52",
                    gdesc:
                        null,
                    good_id:
                        672,
                    gorder:
                        50,
                    gtitle:
                        "歌娜腰果 227G（盐焗味）",
                    id:
                        672,
                    price:
                        56,
                    standard:
                        "/袋",
                    stitle:
                        "歌娜腰果 227G（盐焗味）",
                    tags:
                        null,
                    type:
                        "0",
                    vipprice:
                        48.3,
                    zkprice:
                        48.3
                }
            ],
            [
                {
                    bigpic:
                        "http://mlgwxyt-1254277558.picsh.myqcloud.com/upload/img/171017145154.jpg",
                    category:
                        "60",
                    gdesc:
                        null,
                    good_id:
                        1095,
                    gorder:
                        1,
                    gtitle:
                        "Kitchen-art 不粘炒锅28cm",
                    id:
                        1095,
                    price:
                        164,
                    standard:
                        "/个",
                    stitle:
                        "Kitchen-art 不粘炒锅28cm",
                    tags:
                        null,
                    type:
                        "0",
                    vipprice:
                        139.9,
                    zkprice:
                        139.9
                },
                {
                    bigpic:
                        "http://mlgwxyt-1254277558.picsh.myqcloud.com/upload/img/1510048856531.jpg",
                    category:
                        "60",
                    gdesc:
                        null,
                    good_id:
                        1646,
                    gorder:
                        50,
                    gtitle:
                        "德国 爱慕莎MAMBO原装进口玻璃内胆保温壶家用热水瓶1000ML红色【预售】",
                    id:
                        1646,
                    price:
                        210,
                    standard:
                        "/瓶",
                    stitle:
                        "德国 爱慕莎MAMBO原装进口玻璃内胆保温壶家用热水瓶1000ML红色【预售】",
                    tags:
                        "",
                    type:
                        "0",
                    vipprice:
                        119,
                    zkprice:
                        119
                },
                {
                    bigpic:
                        "http://mlgwxyt-1254277558.picsh.myqcloud.com/upload/img/171002155201.jpg",
                    category:
                        "61",
                    gdesc:
                        null,
                    good_id:
                        369,
                    gorder:
                        0,
                    gtitle:
                        "西班牙进口MAYOR DOMO 玛玉2合1洗衣液",
                    id:
                        369,
                    price:
                        42.8,
                    standard:
                        "/瓶",
                    stitle:
                        "西班牙进口MAYOR DOMO 玛玉2合1洗衣液",
                    tags:
                        null,
                    type:
                        "0",
                    vipprice:
                        33.3,
                    zkprice:
                        33.3
                },
                {
                    bigpic:
                        "http://mlgwxyt-1254277558.picsh.myqcloud.com/upload/img/171002113111.jpg",
                    category:
                        "61",
                    gdesc:
                        null,
                    good_id:
                        980,
                    gorder:
                        0,
                    gtitle:
                        "西班牙原装进口MAYOR DOMO/玛玉厨房清洁浓缩型洗洁精600ml",
                    id:
                        980,
                    price:
                        17.8,
                    standard:
                        "/瓶",
                    stitle:
                        "西班牙原装进口MAYOR DOMO/玛玉厨房清洁浓缩型洗洁精600ml",
                    tags:
                        "",
                    type:
                        "0",
                    vipprice:
                        9.9,
                    zkprice:
                        9.9
                },
                {
                    bigpic:
                        "http://mlgwxyt-1254277558.picsh.myqcloud.com/upload/img/171002154754.jpg",
                    category:
                        "61",
                    gdesc:
                        null,
                    good_id:
                        978,
                    gorder:
                        0,
                    gtitle:
                        "西班牙原装进口玛玉浓缩马赛皂液洗衣液洗衣粉超大量3L",
                    id:
                        978,
                    price:
                        34,
                    standard:
                        "/瓶",
                    stitle:
                        "西班牙原装进口玛玉浓缩马赛皂液洗衣液洗衣粉超大量3L",
                    tags:
                        "",
                    type:
                        "0",
                    vipprice:
                        24.9,
                    zkprice:
                        24.9
                },
                {
                    bigpic:
                        "http://mlgwxyt-1254277558.picsh.myqcloud.com/upload/img/170927131632.png",
                    category:
                        "61",
                    gdesc:
                        null,
                    good_id:
                        1307,
                    gorder:
                        1,
                    gtitle:
                        "土耳其原装进口正品ViKing 蔚净厕所清洁剂 松香型 750ml",
                    id:
                        1307,
                    price:
                        25.8,
                    standard:
                        "/瓶",
                    stitle:
                        "土耳其原装进口正品ViKing 蔚净厕所清洁剂 松香型 750ml",
                    tags:
                        null,
                    type:
                        "0",
                    vipprice:
                        18.3,
                    zkprice:
                        18.3
                }
            ]

        ];

    }
    componentDidMount(){
        document.title = '会员活动';
    }

    render(){
        const {history} = this.props


        return(
            <div className='new-exclusive'>

                <div className='banner'>
                    <img src={require('static/image/vipActive.jpg')} alt=""  />
                </div>

                <div className='goods-list'>
                    <div className="one">
                        {this.titleList.map((item,index)=>  {

                            return(
                                <div key={index}>

                                    <ul>
                                        {this.goods[index].map((i,key)=> {
                                            return(
                                                <li key={key}

                                                    onClick={ ()=>{nativeClick({
                                                        type:2,
                                                        url:i.id,
                                                        id:i.id,
                                                        name:i.title,
                                                        activeType:''
                                                    })}}



                                                >
                                                    <p><img src={i.bigpic} alt=""/></p>
                                                    <div>
                                                        <p className='name'>{i.gtitle} </p>
                                                        <p className='price'>￥{i.zkprice} <span>￥{i.price}</span>
                                                            {/*<button>马上抢</button>*/}
                                                        </p>
                                                    </div>
                                                </li>
                                            )
                                        })}
                                    </ul>
                                </div>
                            )
                        })}



                    </div>


                </div>
            </div>
        )
    }

}

